### ISSUE TITLE
Add BankVic to Banking Products Comparator

### ISSUE THREAD

**Issue by Scott-Wall** [ConsumerDataStandardsAustralia/banking-products-comparator#102]
Please add BankVic to the list of product comparators, URLs as follows;

{
"name": "BankVic",
"url": "https://ib.bankvic.com.au/openbanking/cds-au/v1/banking/products",
"icon": "https://www.datocms-assets.com/28619/1591331902-bv-x5f-logo-x5f-master-x5f-vert-x5f-cmyk.svg"
}

**Comment by vadkor** [comment]
@Scott-Wall, the URL you've submitted is incorrect. Have you tried adding these details in the Banks section of the Comparator manually? The change will have the corrected URL: https://ib.bankvic.com.au/openbanking/cds-au/v1, but even with that your endpoints won't work in the Comparator due to CORS being not implemented (the OPTIONS method is not allowed, but it should be).

If you haven't sent one yet, please email us at cdr-data61@csiro.au to verify your association with BankVic.

**Comment by Scott-Wall** [comment]
@vadkor I have asked our vendor to look at the problem you highlighted above. When you say have I tried adding these details in the Banks section manually I assume you mean forking the repository and adding BankVic's details to the datasources.json file?

**Comment by deepsol-oba** [comment]
@Scott-Wall - have a look at https://cdr-comp.obawv.app/ .. there is a custom entry you can add your URL under banks.

With a CORS Proxy it seems to be working fine https://obawv.app/ .. but that is just a workaround.

**Comment by vadkor** [comment]
> When you say have I tried adding these details in the Banks section manually I assume you mean forking the repository and adding BankVic's details to the datasources.json file?

No, I mean in the Comparator at https://consumerdatastandardsaustralia.github.io/banking-products-comparator/ you can expand the Banks section, click the +(Add) button at the bottom and enter your details.

**Comment by Scott-Wall** [comment]
Ah, thanks. I assume this is not a permanent addition to the list, for that do I still need to fork the repository as detailed here?-  https://cdr-support.zendesk.com/hc/en-us/articles/900002933263-Add-your-organisation-to-the-Banking-Product-Comparator-tool

**Comment by vadkor** [comment]
Your assumption is correct.
Your change has been merged and is live now. You can click the Sync button in the Banks section to load it.
