### ISSUE TITLE
Update to base URI

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/banking-products-comparator#60]
In response to feedback on the implementation call we should modify the comparator so that the base URI stored does not have the `cds-au/v1` component of the URI and the comparator should append this component of the URI at run time.

For instance, the entry in the JSON should be modified from:
`https://api.cdr.acmebank.com.au/cds-au/v1`
to
`https://api.cdr.acmebank.com.au`
The `cds-ai/v1` component is still required but should be added when the end point call is made.

**Comment by vadkor** [comment]
Updating the comparator and the JSON file is only a part of the problem (the lesser one). There is also the local data source config that gets created if any change in the Banks section of the comparator is made. A lot of users get it created just by enabling/disabling/removing the existing entries. If it's created, it has the URIs ending with `/cds-au/v1`.

I propose the comparator should check if the data source URIs (regardless whether they were loaded from the server or from the local storage) end with `/cds-au/v1` and if not then add it. Otherwise use "as is". Maybe we should except from this suffix enforcement the URIs that have _localhost_ as the host name and always use the localhost URIs as they are. Not that it's a problem for our _data-holder_ from _java-artefacts_ - its context path is `/cds-au/v1`, but for some developers and their own implementations it might not be the case. But I can see how this could be confusing.

**Comment by nils-work** [comment]
Hi @JamesMBligh 

I missed the first part of the implementation call where this issue was raised.
Just for my understanding, what was the 'feedback' that was behind this suggested change?

Was it related to aligning to the requirements of the [Registry](https://cdr-register.github.io/register/#tocSregisterdataholderbrandserviceendpoint)?

**Comment by JamesMBligh** [comment]
Hi @nils-work, the issue was that the cds-au/v1 is not strictly part of the base URI as it is a mandatory component of the API URI taxonomy.  This means that the data being captured is different to what would be eventually stored in the register.

As some stakeholders are using datasources.json in lieu of these URIs being available in the registry consistency was seen to be something that would eventually be very helpful.

**Comment by JamesMBligh** [comment]
Hi @vadkor,

> I propose the comparator should check if the data source URIs (regardless whether they were loaded from the server or from the local storage) end with `/cds-au/v1` and if not then add it. Otherwise use "as is". Maybe we should except from this suffix enforcement the URIs that have _localhost_ as the host name and always use the localhost URIs as they are. Not that it's a problem for our _data-holder_ from _java-artefacts_ - its context path is `/cds-au/v1`, but for some developers and their own implementations it might not be the case. But I can see how this could be confusing.

I think your suggestions are a good idea.  Having the comparator check for the context and only adding it if it was missing would definitely help people who have existing URIs in local storage.  Also, the idea of not appending to local URIs would likely be developer friendly.  Good plan.
